### ISSUE TITLE
pattern manifests/*.yaml: no matching files foundgo list

### ISSUE THREAD

**Issue by felix-hxz** [fluxcd/flux2#1187]
pattern manifests/*.yaml: no matching files foundgo list

**Comment by hiddeco** [comment]
This is because we have a pre-build step, see: https://github.com/fluxcd/flux2/blob/main/Makefile#L23-L24. For this reason, it is much better to simply run `make build` than trying to re-produce what is defined there.

Can you please create issues with structured content, that at least describe what you are trying to do, what you are running into, and what you already tried to resolve it? This is the second issue today with just a dump of an error message, which means we as maintainers have to magically figure out what you are attempting to do, costing us time that would probably be better spent elsewhere.
