### ISSUE TITLE
Kustomization controller is unable to access source controller, when NetworkPolicies is enabled

### ISSUE THREAD

**Issue by SlyngDK** [fluxcd/flux2#2152]
### Describe the bug

When bootstrapping with networkpolicy enabled, kustomization controller is unable to access source controller on port 80.

If I disabled networkpolicies it works fine, it looks like there is missing a networkpolicy allowing this.

### Steps to reproduce

Normal bootstrapping with networkpolicies enabled

### Expected behavior

Bootstrap was successful

### Screenshots and recordings

Getting this error when bootstrapping with networkpolicies
```
◎ waiting for Kustomization "flux-system/flux-system" to be reconciled
✗ failed to download artifact, error: GET http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/32a852b62e69d8a7a46663f698969e5800fe301d.tar.gz giving up after 10 attempt(s): Get "http://source-controller.flux-system.svc.cluster.local./gitrepository/flux-system/flux-system/32a852b62e69d8a7a46663f698969e5800fe301d.tar.gz": dial tcp 10.43.27.117:80: i/o timeout
```

### OS / Distro

Ubuntu 20.04

### Flux version

v0.24.0

### Flux check

► checking prerequisites
✔ Kubernetes 1.21.6 >=1.19.0-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.14.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.18.1
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.19.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.19.0
✔ all checks passed

### Git provider

Gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
Network policies are tested in our e2e test suite with Calico. Which CNI are you using?

**Comment by SlyngDK** [comment]
I am using calico as CNI.

**Comment by SlyngDK** [comment]
I am closing this as i have other issues with network policies, in the setup i am testing.

**Comment by MartinEmrich** [comment]
Have the same issue here, with flux 0.37 and Weave Net as CNI.

The issue is one year old and closed, yet I also encountered this.
In my case, the helm-controller was unable to retrieve the helm chart from the source-controller (timed out). `flux install` did only install three network policies for me, none of which allowed access to the source-controller.

First I tried to remove all NetworkPolicies from the flux-system namespace, which made it work.

Then I re-ran `flux install` (restoring the original NP) and added this network policy (which could probably be restricted further): 
````
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  labels:
    app.kubernetes.io/instance: flux-system
    app.kubernetes.io/part-of: flux
  name: allow-source
  namespace: flux-system
spec:
  ingress:
  - {}
  podSelector:
    matchLabels:
      app: source-controller
````

@SlyngDK @stefanprodan how did you solve it a year ago, where could I look?

Thanks
