### ISSUE TITLE
flux with a ImageRepository cannot list image tags in gitlab repository

### ISSUE THREAD

**Issue by joerg-walter-de** [fluxcd/flux2#2447]
### Describe the bug

I have a image repository linking to a self-managed gitlab-Server.

I have bootstrapped flux with `--components-extra=image-reflector-controller,image-automation-controller`.

I have a deployment with an image name in it that refers to an existing image on the gitlab server.

When I set a new image and commit new pods are successfully started based on that image.

But `flux get all` returns an error staging that the repository name is unknown.

### Steps to reproduce

NA

### Expected behavior

The image tags list can be read

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/33499391/154482366-1ed75693-f625-4fc2-81d1-dab491c632bc.png)

### OS / Distro

Windows 10

### Flux version

0.26.3

### Flux check

► checking prerequisites
✗ flux 0.26.3 <0.27.0 (new version is available, please upgrade)
✔ Kubernetes 1.22.4 >=1.20.6-0
► checking controllers
✔ helm-controller: deployment ready
► ghcr.io/fluxcd/helm-controller:v0.16.0
✔ image-automation-controller: deployment ready
► ghcr.io/fluxcd/image-automation-controller:v0.20.0
✔ image-reflector-controller: deployment ready
► ghcr.io/fluxcd/image-reflector-controller:v0.16.0
✔ kustomize-controller: deployment ready
► ghcr.io/fluxcd/kustomize-controller:v0.20.2
✔ notification-controller: deployment ready
► ghcr.io/fluxcd/notification-controller:v0.21.0
✔ source-controller: deployment ready
► ghcr.io/fluxcd/source-controller:v0.21.2
✔ all checks passed

### Git provider

self managed gitlab

### Container Registry provider

self managed gitlab

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by joerg-walter-de** [comment]
Polish

**Comment by kingdonb** [comment]
Can you provide some details about your `ImageRepository` resource and how you created it? (What is the full YAML manifest definition, does it contain a `secretRef`?)

Many times authentication errors masquerade as "not found" because they consider the existence of the target resource a secret covered by the authentication, and revealing the existence makes it easier for attackers to target known resources.

The examples here: https://fluxcd.io/docs/cmd/flux_create_image_repository/#examples show some different authentication strategies; if your GitLab resources are not public, then you will need to be authenticated.

Can you provide some more insight into these details, or does this information help to resolve your issue?
