### ISSUE TITLE
`flux check --pre` fails | Kubernetes API call failed connection refused - arm64 RPI4

### ISSUE THREAD

**Issue by RyzeNGrind** [fluxcd/flux2#2503]
### Describe the bug

Installed flux as per instructions
`curl -s https://fluxcd.io/install.sh | sudo bash`

Ran flux check for prerequisites
`flux check --pre`

### Steps to reproduce

1. Install flux as per guide and described above.
2. Run flux pre-req check. 

### Expected behavior

**Flux is supposed to check and pass all prerequisites before bootstrapping the cluster and using Git as Infrastructure-as-Code source.**

### Screenshots and recordings

```
ryzengrind@moved-gull:~$ curl -s https://fluxcd.io/install.sh | sudo bash
[INFO]  Downloading metadata https://api.github.com/repos/fluxcd/flux2/releases/latest
[INFO]  Using 0.27.3 as release
[INFO]  Downloading hash https://github.com/fluxcd/flux2/releases/download/v0.27.3/flux_0.27.3_checksums.txt
[INFO]  Downloading binary https://github.com/fluxcd/flux2/releases/download/v0.27.3/flux_0.27.3_linux_arm64.tar.gz
[INFO]  Verifying binary download
[INFO]  Installing flux to /usr/local/bin/flux
```
```
ryzengrind@moved-gull:~$ flux check --pre
► checking prerequisites
✗ Kubernetes API call failed: Get "http://localhost:8080/version?timeout=15s": dial tcp [::1]:8080: connect: connection refused
```

### OS / Distro

`Ubuntu Server 20.04.4 LTS arm64`

### Flux version

`flux: v0.27.3`

### Flux check

```
ryzengrind@moved-gull:~$ flux check
► checking prerequisites
✗ Kubernetes API call failed: Get "http://localhost:8080/version?timeout=15s": dial tcp [::1]:8080: connect: connection refused
► checking controllers
```

### Additional context

I am using this [link](https://boxofcables.dev/using-flux2-with-microk8s/) to install FluxCD with Microk8s on a 5-node cluster of Raspberry Pi 4s.

Microk8s has been installed and running on all nodes. I have successfully added all nodes as master and worker nodes to the cluster. My next step was to install and configure FluxCD but alas I cannot pass the prerequisite checks nor can I find any solutions for this on the internet and search engines. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
In the article you linked, it is mentioned that there is a bug in HA mode. If you have joined multiple masters to the cluster, are you running HA mode?

**Comment by RyzeNGrind** [comment]
> In the article you linked, it is mentioned that there is a bug in HA mode. If you have joined multiple masters to the cluster, are you running HA mode?

Yes I tried that as well and it seems to be the same outcome.

```
ryzengrind@moved-gull:~$ microk8s status
microk8s is running
high-availability: yes
  datastore master nodes: 192.168.20.228:19001 192.168.20.225:19001 192.168.20.232:19001
  datastore standby nodes: none
addons:
  enabled:
    ha-cluster           # Configure high availability on the current node
  disabled:
    dashboard            # The Kubernetes dashboard
    dashboard-ingress    # Ingress definition for Kubernetes dashboard
    dns                  # CoreDNS
    helm                 # Helm 2 - the package manager for Kubernetes
    helm3                # Helm 3 - Kubernetes package manager
    host-access          # Allow Pods connecting to Host services smoothly
    ingress              # Ingress controller for external access
    linkerd              # Linkerd is a service mesh for Kubernetes and other frameworks
    metallb              # Loadbalancer for your Kubernetes cluster
    metrics-server       # K8s Metrics Server for API access to service metrics
    openebs              # OpenEBS is the open-source storage solution for Kubernetes
    portainer            # Portainer UI for your Kubernetes cluster
    prometheus           # Prometheus operator for monitoring and logging
    rbac                 # Role-Based Access Control for authorisation
    registry             # Private image registry exposed on localhost:32000
    storage              # Storage class; allocates storage from host directory
    traefik              # traefik Ingress controller for external access
ryzengrind@moved-gull:~$ microk8s disable ha-cluster; microk8s disable dns; microk8s stop; microk8s start; microk8s enable dns; flux check --pre; flux check;
Reverting to a non-HA setup
[sudo] password for ryzengrind: 
Generating new cluster certificates.
Waiting for node to start. .  
Enabling flanneld and etcd
HA disabled
Addon dns is already disabled.
Stopped.
Started.
Enabling DNS
Applying manifest
serviceaccount/coredns created
configmap/coredns created
deployment.apps/coredns created
service/kube-dns created
clusterrole.rbac.authorization.k8s.io/coredns created
clusterrolebinding.rbac.authorization.k8s.io/coredns created
Restarting kubelet
DNS is enabled
► checking prerequisites
✗ Kubernetes API call failed: Get "http://localhost:8080/version?timeout=15s": dial tcp [::1]:8080: connect: connection refused
► checking prerequisites
✗ Kubernetes API call failed: Get "http://localhost:8080/version?timeout=15s": dial tcp [::1]:8080: connect: connection refused
► checking controllers
```

**Comment by kingdonb** [comment]
```
✗ Kubernetes API call failed: Get "http://localhost:8080/version?timeout=15s": dial tcp [::1]:8080: connect: connection refused
```

This error indicates the kubernetes API server is detected as a "localhost" address, which will not be reachable by Flux from inside of the cluster. If `flux check --pre` errors out like this, it means that KUBECONFIG is not set. Do you have a kubeconfig file and can you pass it to Flux?

If you bootstrap Flux with a kubeconfig that says localhost in it, I don't know what will be the result. I'm not sure if this has to do with any microk8s bug really or not. It looks like you just need to set KUBECONFIG. I think this is the right doc: https://microk8s.io/docs/working-with-kubectl – you need to be sure that running `kubectl get nodes` or similar works before running Flux commands. Check if there is any file in `~/.kube/` and if it's missing, write the kubeconfig there like this:

```shell
mkdir -p ~/.kube
microk8s config > ~/.kube/config
```

If I remember correctly, http://localhost:8080 is the address for Kubernetes admin access without any credential required. This might be the address that your `kubectl` tries by default when there is no kubeconfig present. That will not work, in kubeadm it was disabled long ago because it's insecure, maybe red herring here. I think it's just a missing kubeconfig.

Flux should work fine with HA mode and I think that bug report I linked before was probably not relevant (aside: I am not an expert on microk8s but I don't see how this can be considered disabling HA mode, if you have multiple masters in your cluster is that not still HA mode? anyway...) please let us know if this works after! 👍

**Comment by RyzeNGrind** [comment]
It worked thank you. 🙏🏽
