### ISSUE TITLE
Failing reconcilers in Grafana Dashboard is wrong

### ISSUE THREAD

**Issue by eloo** [fluxcd/flux2#2541]
### Describe the bug

Hi, 

i guess the metric for the failing reconcilers in the grafana dashboard is not accurate.

```
          "expr": "sum(gotk_reconcile_condition{namespace=~\"$operator_namespace\",exported_namespace=~\"$namespace\",type=\"Ready\",status=\"False\",kind=~\"Kustomization|HelmRelease\"})",
```

This metric will increase for all reconcilers which are not ready.. so also for running reconcilers it will increase and drop again.

So i guess the metric query needs to be adjust a bit.
Currently i'm not sure what the best would be. But right now the metrics is simple wrong and if we would do alerting on that we would get alerts on every deployment.

### Steps to reproduce

Deploy the grafana cluster dashboard and deploy something

### Expected behavior

We have reliable metrics for failed metrics

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/2631895/158342996-77b677f6-99ef-41a5-8859-7087e97feab1.png)

Here we see a big bump of failing reconciler which is drop again..
So its clearly visible that they are not failing.. they are running.

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by cr1cr1** [comment]
I do not see the issue you have described. To me, while it was a failing state, the counter was > 0, then once fixed, went back to 0. Due to the nature of that "Stat" graph, it will show you a "lump" as a history subgraph.

![image](https://user-images.githubusercontent.com/11889198/168012898-c2fb52a6-1352-4a3f-81e0-e81807ab721f.png)

**Comment by eloo** [comment]
Hi, 
in our case it looks like this:

![image](https://user-images.githubusercontent.com/2631895/188882936-c96214c4-87af-487e-92b9-e880ca765e5b.png)

the status is going from `True` to `False` and `Unknown` for some kinds..

But all are recovering after a few minutes.. 

![image](https://user-images.githubusercontent.com/2631895/188883766-a58f5373-6099-43bf-b360-13a94d52f361.png)

And here we see that we have short spikes of `False` which are recovering itself.. So they are not really failing.. 

Any ideas why the metrics are shown like this? Can this maybe some kind of backpressure?

**Comment by stefanprodan** [comment]
Every time a HelmRelease chart version is updated, the HelmRelease will error out with `HelmChart not ready` and `Ready` is set to `False`. After a couple of seconds, the source-controller downloads the chart and the HelmRelease becomes ready again. This is how helm-controller currently works, you also get an alert (via notification-controller) every time the chart version changes that the HelmChart not ready. Many users complied about this behaviour including myself, @hiddeco is working on refactoring helm-controller so maybe we can finally fix this.

**Comment by eloo** [comment]
@stefanprodan thanks for the explanation 👍 
at least that matches the behaviour i'm seeig..

so for now i can implement a workaround for our alerting to observe a bit longer the values. 

but i'm looking forward to see this fixed :)

**Comment by stefanprodan** [comment]
What I think helm-controller could do, is wait for the HelmChart to be reconciled and only then error out if that fails, waiting with a timeout set for upgrade/install. cc @hiddeco

**Comment by hiddeco** [comment]
Waiting for objects is kind of unnatural for something like a reconciliation loop because it holds up the queue by taking the worker hostage. Generally speaking, they should fail fast and re-queue to give other things a chance to be processed while whatever it fails on is being addressed by something else in the distributed space. This theoretically results in a higher throughput.

In addition, `Ready=False` is not a failure. It means that the object is not in-sync compared to desired state (or it can not be assessed, or is actively being worked on to ensure it will match state). Because of this, you would only configure alerts for when they are in this state for a longer period of time, as things are expected to end up in `Ready=True` state eventually. (The fact that it goes from `True` -> `False` -> `Unknown` is already sorted in my refactor work).

Given this, I am not sure if this requires changing other than ensuring that the events that are also broadcasted at present (and thereby confusing people forwarding them to e.g. Slack) are e.g. only emitted when it reaches a certain failure count threshold.

**Comment by stefanprodan** [comment]
Fixed in https://github.com/fluxcd/flux2-monitoring-example
