### ISSUE TITLE
Please get rid of your CLI and use the standards

### ISSUE THREAD

**Issue by rfftrifork** [fluxcd/flux2#2728]
### Describe the bug

The existence of a cli for managing and installing Flux is a problematic and legacy pattern, following reasons

*  Why do I even need this? Let me state the obvious, there's reasonable standards for this that could be followed
* A CLI requires me to learn a new set of commands that I only use for one specialised task
* If I (as most people do or are moving towards these days) use infrastructure as code, now I need to write scripts anyway
* It pollutes my system, I already have way too many tools that I only use on occasion because azure, openshift, vuejs etc etc all think I need a tool for their task - please stop the madness, it's insane!
* Most of these tools are not in a package manager, which means they do not get updated (no! I am not going to manually maintain all the tools). It means they are mostly outdated, and potential security risks

Can we please put a stop to creating a CLI for every little framework or tool out there? If it is not general purpose then think really hard if you need this. It is frustrating having to install yet another tool, that I'm going to use for 15 commands and forget. Tbh. this should be considered a really nasty anti pattern, and your time would be better spent on creating a kubernetes operator and CRDs for running and bootstrapping your systems in a reasonable way

### Steps to reproduce

E.g. install Flux or similar following the standard setup

### Expected behavior

That there's an operator I and install and standard `yaml`-setups I can write, so I actually do infrastructure as code (yes, I consider my CD part of the infrastructure)

### OS / Distro

N/A

### Flux version

N/A

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
If you don't like our CLI then don't use it. You can install Flux with [kubectl](https://fluxcd.io/docs/installation/#dev-install).

**Comment by hiddeco** [comment]
The CLI is complementary, and we actually follow standards (for a precise list, see: https://github.com/fluxcd/pkg/tree/main/runtime#supported-standards).

As Stefan already suggests, Flux can be installed without the CLI using plain YAML manifests. All of our controllers also have these individually published (see e.g. assets in https://github.com/fluxcd/source-controller/releases/tag/v0.24.4). In addition, any resource can be viewed and inspected using `kubectl`. Plus we offer a [Terraform provider](https://github.com/fluxcd/terraform-provider-flux) to declaratively configure the bootstrapping. 

As a last note, I do not like the tone of voice of your complaint. It is OK to make suggestions for improvements, it is not OK to make this rant and/or attack about the quality of software.

Flux is the result of hard work from a relatively small group of maintainers, (voluntarily, even if backed by a for-profit company) devoting countless of hours to build something that's OSS, and free for you to use. To then come with such a strong stance, without being further involved in the community, is not how you get things done.

**Comment by rfftrifork** [comment]
@hiddeco sorry, you're right, my tone isn't fair to the effort and work put in. That said, I do stand by the basic point that the effort put into a CLI is better put elsewhere, simply for the reasons, does it offer anything that's actually makes it worth the effort, and do the users even what it - most serious tech people I know actually get annoyed by such tools more or less for the reasons stated above (however badly phrased by me)

Regarding the documentation of this knowledge, I will then request that it is added to this site: https://fluxcd.io/docs/installation/ where I would expect a lot people to look for installation instructions (it's where I was looking). And I never got further because of the frustration of having to install yet another CLI for a special purpose task that don't need a CLI and no obvious references to the solutions referenced in the answers above

**Comment by kingdonb** [comment]
A lot of care is taken to ensure the docs are accessible and easy to follow, I'm sorry this experience has been frustrating.

There's a lot of secret handling and repository structure stuff that is easy to get subtly wrong in potentially dangerous ways when handled manually. It's also easy to "miss the point" at this junction, one can install Flux in a cluster in a way where Flux itself is not itself managed via GitOps, only some apps, and as a result the process of checking that Flux is up to date or actually upgrading Flux becomes a lot less transparent and a lot more difficult to ensure it has been done correctly overall.

IOW, users should not have to understand exactly what we're doing before we can get a working Flux installation, correctly installed, to get hands-on and start learning how Flux works. We expect that many people can't really effectively manage all these new concepts at the same time as performing a series of opaquely complicated manual steps.

The idea is to install best practice advice from the very beginning, such that users learn how to manage resources in the GitOps way, starting with Flux itself. If we present a bunch of steps and users read along, trying to adapt them for their purposes, some users will inevitably make different choices and fail to conform due to lack of understanding owing to being in early stages of learning how Flux works, folks fall out of the funnel one way or another. If it presents as a single command "bootstrap" and encapsulate all those steps in the abstraction, the hope is that it actually lowers the activation energy to get through to the point where a working installation is set up according to best-practices and users can get on with using Flux.

It's also handy that the CLI includes a `check` and `check --pre` to avoid common errors caused by starting with a Kubernetes version that is too early and known not to work, or something else we can detect before installing. This is every bit as much about lowering the burden of maintainers who have to answer questions when things go wrong for users.

The full list of steps performed by Bootstrap is really quite long when you unpack it; there is a design intention or "artist's vision" we think is best absorbed intact without too much variance while still learning how Flux should work. So a goal of the bootstrap command in the CLI is related to conceptual compression, a concept I learned in the Rails community. We should not need to unpack the components or ideas which can be accepted in their generic form and may remain undifferentiated, until we have a need to understand them further, or a special need to differentiate them somehow.

I'd like to acknowledge that different people have different learning styles and our documentation is far from perfect. We are open to improving the docs, and we have some ongoing efforts that can use more help. That being said, the CLI is available for every platform and architecture, with plenty of options to choose from regarding installation methods. Please be open to try it, this is the recommended entrypoint for starting with Flux, we think, for good reason.


@rfftrifork On the other hand, there is a guide to install/bootstrap Flux on platforms wherever Bootstrap is not supported:

https://fluxcd.io/docs/use-cases/azure/#flux-installation-for-azure-devops

This alternative approach is not highlighted for cases where it is not required to do things this way because it's fairly complicated; we think the "bootstrap" process is much easier and so recommend bootstrap for new users because it sets Flux up managing itself via GitOps.

The instructions that *avoid using* the CLI as presented in the document linked above are fairly involved, and though they do still honor GitOps principles, it's far from straightforward for new users, many of whom will likely have a lot to learn if they haven't used Flux before. So part of the intention and the value of the CLI is to get Flux users to the finish line quickly and in time to leave room for reading docs and understanding those concepts.
