### ISSUE TITLE
Implement `flux create secret oci`

### ISSUE THREAD

**Issue by stefanprodan** [fluxcd/flux2#2910]
Add a new command for generating image pull secrets of type ` kubernetes.io/dockerconfigjson`:

```sh
flux create secret oci ghcr \
 --username=<github-username> \
 --password=<github-token> \
 --url=<ghcr-URL>
```

The implementation PR should be made agains the `oci` branch, ref: #2856

**Comment by stefanprodan** [comment]
Implemented in #2920

**Comment by aabmets** [comment]
@stefanprodan 
Why does `flux create secret oci` produce a secret in which the `.data.dockerconfigjson` value is not base64-encoded? 

In your [documentation](https://fluxcd.io/flux/components/image/imagerepositories/#secret-reference), and I quote: "The secret is expected to be in the same format as the [docker config secrets](https://kubernetes.io/docs/concepts/configuration/secret/#docker-config-secrets), usually created by kubectl create secret docker-registry". The kubectl command produces a base64-encoded `.data.dockerconfigjson` value.

If you state that Flux expects the secret to be in the format produced by the kubectl command, then how is the `flux create secret oci` command supposed to produce a valid docker-registry secret, if it does not produce a base64-encoded `.data.dockerconfigjson` value? 

This is confusing and undocumented behavior. Either the documentation should be improved to explain this deviation from the expected behavior, or the flux command should be fixed to conform to the output of the kubectl command.

**Comment by stefanprodan** [comment]
We use `stringData`, so secret scanners and humans would see that you are committing unencrypted sensitive information to Git.
