### ISSUE TITLE
Helm Release ignores fields explicitly set to null

### ISSUE THREAD

**Issue by leon-marcel** [fluxcd/flux2#3298]
### Describe the bug

If i try to set a value to null - Flux ignores the whole key / value pair. I try to install a Helm Chart as Flux Helm Release. I set `securityContext.secCompProfile to null `but if Flux deploys the Chart and if i gather the values of the release the whole entry is missing. This leads to  problems because sometimes it's necessary to explicitly overwrite fields with null.

### Steps to reproduce

1. Create Helm Release and set a dictionary to null 
2. For Example: 
```apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kyverno 
  namespace: kyverno
spec:
  chart:
    spec:
      version: ">=2.6.0"
  values:
    namespace: kyverno
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
      privileged: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      seccompProfile: null
    testImage:
      repository: busybox
```
4. Let FluxCD Deploy the Helm Chart
5. Execute `helm get values kyverno -o yaml`
6. Output contains: 
```securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  privileged: false
  readOnlyRootFilesystem: true
  runAsNonRoot: true
```
8. The seccompProfile Entry is missing
9. This leads to Problem because now it gets overwritten by OCP and leads to Permission problems

### Expected behavior

If i try to install it with my local helm client it works as expected and the `helm get values kyverno` Command does contain the `seccompProfile: null `entry. Flux should work accordingly.

### OS / Distro

OCP

### Flux version

v0.36.0

### Flux check

N/A 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by leon-marcel** [comment]
Ok it seems like Kustomize is the problem. I merge two HelmReleases together with a Kustomization and deploy this Kustomization with a FluxCD Kustomization. It seems like Kustomize ignores null values. So i'm not sure if this is the right place to gather help.

**Comment by leon-marcel** [comment]
This seems to be a problem with the way Kustomize executes strategic merges. Closing this issue.

**Comment by frimik** [comment]
Sorry for visiting an issue you closed @leon-marcel .. but I'm finding this issue because of a case where it seems our Flux is **NOT** applying the explicitly intended emptying of the `spec.conversion` field in the following manifest:

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  conversion: null
```

The object on the server (some extra details cut away for brevity):
```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
spec:
  conversion:
    strategy: Webhook
    webhook:
      clientConfig:
        service:
          name: external-secrets-webhook
          namespace: external-secrets
          path: /convert
          port: 443
      conversionReviewVersions:
      - v1
```

If I diff, build or apply this with either of: 
- `kubectl diff -f resource.yaml`
- `kubectl apply -f resource.yaml` 
- `kubectl apply -k .`
- `kustomize build . | kubectl apply -f -`
 
It all properly diffs and updates these resources as expected.

Explicitly applies the "empty" field value to the server, which because the field is "non-nullable" empties it and then applies whatever default values exist according to the openapiv3 schema.

When Flux reconciles a Kustomization that is pointing to a bare source directory of yaml it seems it does not actually send that field to be applied to the server at all. This seems unexpected.

According to [this](https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definitions/#defaulting-and-nullable) I interpret it as `null` should be explicitly sent to the server and handled there, depending on whether the field is nullable or not.. (In this case, it is not nullable, thus should be "emptied").

I've ensured the target resource has no issues with managedFields etc.
I even updated the target resource to add some bogus field in it elsewhere, and Flux reconciled it and removed that value, to verify it is indeed syncing that object properly otherwise.

It seems like it's indeed an issue in the kustomize libraries and I'm moving on there to try and find the exact issue or see if I can patch it somehow.
