### ISSUE TITLE
Central Flux instance vs. HelmRelease vs. common base files

### ISSUE THREAD

**Issue by TomyLobo** [fluxcd/flux2#3499]
### Discussed in https://github.com/fluxcd/flux2/discussions/3494

<div type='discussions-op-text'>

<sup>Originally posted by **TomyLobo** January 18, 2023</sup>
I'm using a central Fluxv2 instance on a management cluster and I have 2 additional clusters: app1 and app2.
All 3 clusters have the same infrastructure components, with (for simplicity's sake) the same configuration.

Relevant for this are 3 Flux resources for each cluster:
1. Kustomization A, which sits at the top level for each cluster and rolls out 2 lower-level Kustomizations for apps and infrastructure.
2. Kustomization B, which is the lower-level Kustomization for the infrastructure components.
3. HelmRelease C, which installs one of the infrastructure components, external-dns.

The flux-system Kustomization of the management cluster rolls out A.
A rolls out B.
B rolls out C.

A and B are in cluster-specific files, C is in a common base file.

In order to roll out infrastructure components on the app1/2 clusters, I need to add a kubeConfig key to the spec of one of the 3 resources.
If I add kubeConfig to A, I get:
```
Kustomization/flux-system/app1-infrastructure dry-run failed, error: no matches for kind "Kustomization" in version 
"kustomize.toolkit.fluxcd.io/v1beta2"
```
If I add kubeConfig to B, I get:
```
HelmRelease/component1/component1 dry-run failed, error: no matches for kind "HelmRelease" in version "helm.toolkit.fluxcd.io/v2beta1" Namespace/component1 created
```
If I add kubeConfig to C, I'm overwriting the HelmRelease objects for the other clusters, since they're the same cluster+namespace+name.

The errors in cases 1 and 2 are due to the remote clusters missing Flux's CRDs, so I considered installing those on the remote clusters.
But without a Helm Controller on those clusters, my HelmRelease wouldn't get installed, right?
Is there a way to have all 3 of these:
1. Just one central Flux instance
2. Rolling out a Helm release via Flux on a app1/app2
3. Describing that Helm release with a common base file for management/app1/app2

Maybe Flux isn't designed for this, but it seems like a very basic use case of the multi-cluster feature.
So I hope I'm the problem and not Flux :)</div>

**Comment by kingdonb** [comment]
I think maybe you have not seen the `kubeConfig` field on `HelmReleases` and `Kustomizations`

This is the tool for remote access from one Kubernetes cluster to another, it works with CAPI secrets or there are some instructions for loading a kubeconfig into a secret, if you aren't using CAPI:

https://fluxcd.io/flux/components/helm/helmreleases/#remote-clusters--cluster-api

There is a similar doc for `Kustomizations`:

https://fluxcd.io/flux/components/kustomize/kustomization/#remote-clusters--cluster-api

Hope this helps! I think you had the right idea, just didn't find this. Let us know if that answers your question please, and thanks for using Flux!

**Comment by TomyLobo** [comment]
@kingdonb I have seen that field, but that doesn't help, see what I wrote in the original post:
> If I add kubeConfig to [the HelmRelease] C, I'm overwriting the HelmRelease objects for the other clusters, since they're the same cluster+namespace+name.

I have 1 base file that contains the base HelmRelease definition.
As far as I know, there are 2 fields I cannot override: name and namespace
So if I roll out the same file for 2 clusters and I'm using the central approach, both times, the HelmRelease object ends up on the management cluster and since they both have the same name+namespace, there's a conflict

**Comment by kingdonb** [comment]
I see, that is a different problem than what I understood when I first read your post 👍 so your issue is that you need to replicate the HelmRelease across different environments, but Flux does not support any replicating mechanism like "KustomizationSet" that you could derive slightly different instances of the same HelmRelease from.

https://github.com/gitops-tools/kustomization-set-controller

There is a paid solution in the Weaveworks "Weave GitOps" product that is along those lines, I guess that is why this is not maintained now, because it competes in the same space. But this Kustomization Set is along the lines of what I think you're asking.

There are many approaches you can use to make a bunch of replicated copies of the same Flux resource. I think this will not be solvable in Flux itself, because the `HelmRelease` manages one target Helm release (it maps to one instance of a current Helm install with a helm secret that holds the accounting), and there is no way I can conceive of that it will be extended to manage many instances without creating a problem right now. The approach is to create many `HelmReleases` if you want to manage many instances of the same app on many clusters.

You can create them severally in different ways with Kustomize, and maybe that's what the subject of this issue is really. I think I misinterpreted the design of your question at first.

**Comment by TomyLobo** [comment]
Your solution is to autogenerate multiple HelmReleases, kind of like StatefulSet does for Pods?
That would require the ability to add per-cluster patches and I don't see that in KustomizationSet.

I need to be able to roll out external-dns everywhere from a single base file, but with a different txtOwnerId, set in a patch for each cluster.

**Comment by kingdonb** [comment]
For features that you found lacking in KustomizationSet, you might find them in better abundance on Kluctl

I'm not sure if it supports that feature, but as KustomizationSet is not maintained it's definitely more likely to land in Kluctl.

I think these behaviors are possible if you will write an overlay for each cluster, but that's going to require a bit less dynamism perhaps.

**Comment by TomyLobo** [comment]
https://www.reddit.com/r/kubernetes/comments/zctxj5/comment/iz22i0h/?utm_source=share&utm_medium=web2x&context=3
> Kluctl converts Helm Charts into plain manifests
One of the reasons I'm using Flux instead of ArgoCD is that it doesn't convert Helm Charts into plain manifests.
I'd rather not go back on that.
Also, kluctl says it's an alpha?

**Comment by kingdonb** [comment]
Please read more about Kluctl. It's not all flux-replacement.

https://kluctl.io/docs/template-controller/spec/v1alpha1/

The part we're interested in here is the Template Controller. It can be installed independent of the rest of Kluctl. The author there is talking about one part of Kluctl, you don't have to use all the parts, and I agree I wouldn't use that part either.

You wouldn't replace your HelmReleases with KluctlDeployments, (though some users might – we do commonly have users requesting dry-run and diff features in HelmRelease, which we don't offer now)

If you don't like that it's in Alpha, well I do have a solution I could offer you (GitOpsSets in Weave GitOps) that is supported, but it's also a paid option, and I frankly haven't done any feature comparisons against Kluctl to say whether or not it's a favorable comparison. Both solutions are in active development, as are any others that are interesting. Our solution might also very well be alpha, both solutions are likely supported too; I would still recommend you try it if it solved an itch for you.

Whether you're willing to consider paid options or not, is definitely going to narrow down your choices. I haven't really used Kluctl yet, I'm pointing at it because a person I know who part built KustomizationSet and works on our paid solution, which GitOpsSet derives from, is saying that (paraphrased) [Kluctl is]...

> it's a replacement for KustomizationSet (and a reason why that one is no longer developed as an OSS solution alongside our paid solutions.)

We realize that many people want only open source solutions, and so we will go to some trouble to even develop competitive solutions with our own products, even if only so we can still say that there are OSS avenues to solve a problem, and give us a chance to talk about our paid solutions which I think are better without pissing people off... but not to belabor the point, we're not going to develop a paid solution *and* an OSS solution when there are free solutions that are already competitive.

Given that he's put a lot more time in on this problem than I have, and his perspective is more deep than mine own based on having worked on a particular solution for the problem, I think it's worth a second look before dismissing Kluctl.

---

It looks like this Kluctl has more than one business end, and it has modes that aim to replace Flux controllers as well as other modes that aim to work together with existing controllers in Flux and do orthogonal jobs in a more stand-alone mode. I'm not suggesting the more extreme "flux-replacement" mode of Kluctl, (but once you are using it, they have their foot in the door... then there are many possibilities and you might want to look at all of them.)

From the docs, it looks like the Template Controller is designed to solve [two problems](https://github.com/kluctl/template-controller#use-cases), one of them being managing templates for even dynamic environments (including for pull requests) and the other being transformation of secrets/objects.

I think you may resist this solution because you simply don't want to have multiple definitions of HelmRelease in your cluster, (and I guarantee that Flux does not have a solution to that right now. The solution is templates, but not inside of HelmChart)

That Kluctl solution might be in alpha, but its Template controller is also apparently orthogonal to the bits that unpack Helm Charts into plain manifests. And I don't want to contradict the main dev of Kluctl about what it's for, but that is a single line of a Reddit conversation taken out of context, I don't think it makes sense to apply it here.

**Comment by stealthybox** [comment]
@TomyLobo You could use the same HelmRelease for external-dns in every cluster if it references its values from a ConfigMap that is different in each cluster. See the `valuesFrom` field.

Using central ConfigMap(s) to hold global values can help you variate constants while keeping the infra declarations the same.

**Comment by TomyLobo** [comment]
> @TomyLobo You could use the same HelmRelease for external-dns in every cluster if it references its values from a ConfigMap that is different in each cluster. See the `valuesFrom` field.
> 
> Using central ConfigMap(s) to hold global values can help you variate constants while keeping the infra declarations the same.

Maybe I don't understand what you're suggesting, but how would that get around the issue that the HelmRelease objects for my 3 clusters would all sit in the management cluster under the same namespace+name, i.e. conflict with one another?
That's the issue I outlined here:
https://github.com/fluxcd/flux2/issues/3499#issuecomment-1405597890

**Comment by kingdonb** [comment]
They wouldn't be hosted on the management cluster, they would be on the target cluster (where they can access the configmap in their local context).

Flux reaching across clusters is sort of an anti-pattern IMHO. You can do it, but your templating solution has got to be able to create the three HelmReleases with three different names.

If they are in the same namespace, on the same cluster, then it follows that they all have access to the same service accounts in the namespace. This is antithetical to a multi-tenant configuration, the HelmReleases have to be in **at least** different namespaces, and ideally they are on completely separate clusters, (so they can really have the same name and namespace, if you wanted.)

I guess you're using the `kubeconfig` field on HelmRelease to reach into another cluster and manage Flux resources there, without installing Flux on the target cluster. That's a totally valid way of managing many clusters, but there is "hard multi-tenancy" where workloads that must be kept separate are divided by a cluster boundary and "soft multi-tenancy" where the resources are hosted on a same cluster and control plane, but they are divided through RBAC and don't share secrets.

Is that what you are doing? You can override `namespace` in a kustomization overlay, but not `name`. So theoretically what you're trying to do, it sounds like, should still work – but I'm not sure I've understood completely the issue you have right here.
