### ISSUE TITLE
Flux uninstalled tenant's namespace after timeout during flux bootstrap

### ISSUE THREAD

**Issue by DanielAntos90** [fluxcd/flux2#4032]
### Describe the bug

During installing of flux-system using flux boostrap gitlab the timeout occurred in CustomResourceDefinition/gitrepositories and CustomResourceDefinition/helmreleases. After this timeout the flux system was automatically uninstalled. During this uninstallation the flux system delete also tenant's namespace with all of its objects, but none of those object was specified in tenant configuration. Tenant has only namespace specified in configuration.

### Steps to reproduce

Run command

lux bootstrap gitlab \ 
  --hostname=gitlab.company.com --owner=kubernetes \ 
  --repository=flux-platform-admin \ 
  --branch=master \ 
  --path=clusters/production --context=production \ 
  --secret-name flux-system-auth

### Expected behavior

flux is installed without deleting of tenant namespace

### Screenshots and recordings

log output:

flux bootstrap gitlab \ 
  --hostname=gitlab.company.com --owner=kubernetes \ 
  --repository=flux-platform-admin \ 
  --branch=master \ 
  --path=clusters/production --context=production \ 
  --secret-name flux-system-auth 
Please enter your GitLab personal access token (PAT):  
► connecting to https://gitlab.company.com/ 
► cloning branch "master" from Git repository "https://gitlab.company.com/kubernetes/flux-platform-admin.git" 
✔ cloned repository 
► generating component manifests 
✔ generated component manifests 
✔ component manifests are up to date 
► installing components in "flux-system" namespace 
✗ timeout waiting for: [CustomResourceDefinition/gitrepositories.source.toolkit.fluxcd.io status: 'Terminating', CustomResourceDefinition/helmreleases.helm.toolkit.fluxcd.io status: 'Terminating', Namespace/flux-system status: 'Terminating']

### OS / Distro

macOS 13.4.1

### Flux version

v2.0.0-rc.3

### Flux check

✔ Kubernetes 1.24.13 >=1.20.6-0

### Git provider

gitlab

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by makkes** [comment]
Flux itself doesn't uninstall anything when the bootstrapping fails so I suppose it's something in your repository that causes this.

**Comment by kingdonb** [comment]
It looks to me like you may have tried to install Flux into a namespace that was terminating. Then any resources you could have created would have been deleted with the `flux-system` namespace. There might have been something stuck; are you reusing a cluster for experiments, or is this a production system?

Please ensure that the `flux-system` namespace isn't `Terminating` before you begin the bootstrap.

If the Flux Kustomization fails (times out without becoming ready) and it rolls back a change as a result, you might see some resources that were created getting deleted then. If a namespace is deleted, anything in that namespace will be deleted with it. That's part of the design of how Kubernetes itself works. You can't have resources in a deleted namespace, they are all sent the delete signal in the namespace's "Deleting" phase.

Any resources that are new when a Kustomization fails to apply, could be deleted, even if the `prune` flag is not enabled because the Kustomization applies itself atomically. It could be caused by any resource that fails to become ready. But the Terminating state most likely comes from a Namespace that is stuck in Terminating.

`flux uninstall` between experimental retries could help with this as well. It cleans up the namespace and the finalizers.
