### ISSUE TITLE
Flux able to get helm repo index.yaml but failing to fetch chart 401 unauthorized

### ISSUE THREAD

**Issue by ikatolkar** [fluxcd/flux2#4078]
### Describe the bug

Hi,

We're using JFROG artifactory as helmrepository. 

The flux helmrepo is configured to use a secret containing username and artifactory auth token.

The helmrepository is able to fetch index.yaml. But its not able to fetch the chart. Its failing with 401 unauthorized. But I am able to fetch the chart manually via curl using the same token.

```
kubectl get helmrepo

svc-helm-prod-virtual       https://artifactory-a.company.com/artifactory/svc-helm-prod-virtual/      3d    True    stored artifact for revision '2f46d1bb7eb2843e75ceb20728dbc38a9c007315343c86e2fd1a3842d0d79cc8'

kubectl get helmrelease

r1-a-etcd  16m     False   HelmChart 'etcd-lab/etcd-lab-r1-a-etcd' is not ready

kubectl get helmchart

etcd-lab-r1-a-etcd   etcd            1.1.1     HelmRepository   svc-helm-prod-virtual   18m     False   chart pull error: chart pull error: failed to download chart for remote reference: failed to fetch https://artifactory-a.company.com:443/artifactory/api/helm/svc-helm-prod-virtual/etcd-chart/etcd-1.1.1.tgz : 401 Unauthorized
```

I am able to pull the same chart using curl, with the same credentials used in the helmrepo:

`curl -u myuser:'mytoken' -X GET https://artifactory-a.company.com:443/artifactory/api/helm/svc-helm-prod-virtual/etcd-chart/etcd-1.1.1.tgz -o myfile.tgz`

Logs from source controller:

`{"level":"error","ts":"2023-07-17T05:01:30.385Z","logger":"controller.helmchart","msg":"Reconciler error","reconciler group":"source.toolkit.fluxcd.io","reconciler kind":"HelmChart","name":"etcd-lab-r1-a-etcd","namespace":"etcd-lab","error":"chart pull error: chart pull error: failed to download chart for remote reference: failed to fetch https://artifactory-a.company.com:443/artifactory/api/helm/svc-helm-prod-virtual/etcd-chart/etcd-1.1.1.tgz : 401 Unauthorized"} `

Any guidance will be much appreciated.

Thanks

### Steps to reproduce

1. Setup flux helmrepo for jfrog artifactory, that uses username and auth token as credentials
2. Check helmrepo is working fine, no auth issues, its able to pull index.yaml
3. Create helmrelease, verify it fails to pull helm chart due to 401
4. Use curl and same credentials to pull chart, verify it works

### Expected behavior

If creds are working for helmrepo and manually via curl, they should work for pulling helmchart too.

### OS / Distro

OpenShift 4.10.30

### Flux version

source-controller:v0.25.10

### Flux check

N/A

### Container Registry provider

jfrog

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by hiddeco** [comment]
This happens because your `HelmRepository` has a `https://example.com` defined, while the `index.yaml` advertises `https://example.com:443`. Due to this, and with the introduction of `--pass-credentials` in Helm because of a [security advisory](https://github.com/helm/helm/security/advisories/GHSA-56hp-xqp3-w2jf), credentials are [no longer automatically passed along when the hosts differ (including any port mismatches)](https://github.com/helm/helm/blob/32c7e37e32ada5b92c6a3ec88afbed11e9923a60/pkg/getter/httpgetter.go#L72-L75).

To prevent this from happening, you either need to configure the `.spec.url` of the repository to match the advertised host _including_ the port, or set `.spec.passCredentials` to `true`.

**Comment by ikatolkar** [comment]
Thanks, that works
