### ISSUE TITLE
Change the default behaviour for components-extra from opt-in to opt-out scenario

### ISSUE THREAD

**Issue by gecube** [fluxcd/flux2#4443]
### Describe the bug

Good day!

My typical usage of fluxcd is to install all available components like `components-extra='image-reflector-controller,image-automation-controller'` even they are not used in the particular cluster. It is annoying to add this command line argument every time and it is easy to forget it. So I think that it would be beneficial to change the default setting to install both image-reflector-controller and image-automation-controller and give the users of FluxCD option to disable them if necessary. 

### Steps to reproduce

-

### Expected behavior

-

### OS / Distro

any

### Flux version

2.0.0-rc.1

### Flux check

-

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kingdonb** [comment]
Thanks for the feedback! The decision to leave these controllers out by default is not just for deployment size, it's also a matter of promoting the more desired and better secured behavior. The default behavior of Flux is read-only in a Git repo. The flux bootstrap provisions a read-only deploy key when you bootstrap it against an SSH repo. All decisions about which controllers go in the default set stem from this original consideration, read-only behavior of a standard Flux installation.

We are now more broadly promoting the use of OCI Repositories to fill in some gaps where Image Update Automation does not fill the entire bill, or where it results in sub-optimal configurations. Granted the IUA is a standard and a staple in Flux, and I think it's not going anywhere soon. There are solid automation techniques today that users can adopt that will not require a target cluster to have any read-write token at all, and Flux can keep up with the latest release through `spec.semver` or through CI workflows that update a configmap or similar while the manifests and the release engineering are in process.

I do not think this default (or this disposition against read-write tokens in the cluster) is likely to change, even if the image update automation is here to stay as I think it is. Since the removal of libgit2, the performance has improved with other characteristics as well, it's fine to debate. And mine is not the final say, but I'm happy to explain the reasoning as I understand it, and I hope that we can get more Flux users to adopt OCI based automations, these ones that do not violate the security of the Single Source of Truth. Opening up a back-channel that the cluster or anyone with access to Flux's deploy key secrets can write arbitrary changes into Git, is sub-optimal for security IMO.

Push-based workflows on OCI make the most sense because your CI almost definitely already had permission to write to the OCI repo, since you're building images, and it can be enabled with workload identity which doesn't require to handle secrets.

**Comment by stefanprodan** [comment]
The install and bootstrap commands are GA, doing this would mean braking the current behaviour which we can't do, people who rely on the install and bootstrap commands for upgrades, will end-up with more controllers than desired.

**Comment by gecube** [comment]
@stefanprodan thanks, fair enough.
