### ISSUE TITLE
dependsOn dependency chains slow down kustomizations considerably

### ISSUE THREAD

**Issue by wvh** [fluxcd/flux2#4739]
### Describe the bug

For a Flux setup that involves a lot of chained Kustomizations using `dependsOn`, for example:

`bootstrap --> controllers --> databases --> post-config --> app1 / app2 / app3`

The first synchronisation is necessarily slow because Flux has to create the cluster resources from scratch. However, further simple changes to business apps trigger all Kustomizations and have to wait for the health checks to pass.

This isn't strictly a bug, but it would be nice to have a kind of dependency where a Kustomization – like `bootstrap` – is assumed healthy if it has passed at least once, so a small change to a Kustomization at the end of the chain would not have to wait a potentially long time to be applied because Flux is crawling through the whole dependency chain.

The logic here is that most "infrastructure" Kustomizations rarely change, while "app" Kustomizations change very often.

It is not obvious to me if Flux can be tricked into doing that currently without removing the `dependsOn` logic entirely.

### Steps to reproduce

1. Create a logically ordered chain of Kustomizations that depend on each other
2. Make regular changes to a Kustomization at the end of that depedency chain
3. Consistently wait a long time for small changes to be applied

### Expected behavior

I guess Flux works as described, though often Kustomizations run without direct changes, and Flux should be faster and either notice that by itself or take a hint from a hypothetical field that implies the nature of the dependency.

### OS / Distro

N/A

### Flux version

v2.2.3

### Flux check

N/A

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by stefanprodan** [comment]
See here an example on how you can speed up the dependencies check with  `--requeue-dependency` https://fluxcd.io/flux/installation/configuration/vertical-scaling/#increase-the-number-of-workers-and-limits

**Comment by kingdonb** [comment]
Besides setting a shorter value for `--requeue-dependency` the key to making changes progress rapidly is to reduce interdependency and add receivers. Those are both complicated issues and you can't always remove a dependency link from the chain, but requeue-dependency has a default setting of 30s, you can instantly make this issue much better by setting it to a lower value in the range of 2-5s. You can see a chain of dependencies like yours, with length 4, reduce the wait from over 2 minutes to a best-case of less than 30s.

Teasing apart your sources is the next key. If an update to "app1" comes from a change the bootstrap repo, then it will necessarily trigger all the dependencies in the line that came from bootstrap repo, because every Kustomization downstream of the Source that changed needs to perform a dry-run and check for changes. But if each app is automated with an OCI Repository, the parent Kustomizations need not be triggered first. You can use semver wildcards to push out the latest version of an OCI-hosted app without a change in the Flux configuration upstream of it.

Then you can start seeing your app deploy progress with no requeues, in as little as 2-5s of being pushed. This fast timing will only be possible with the aid of a Receiver webhook.

**Comment by denniseffing** [comment]
@kingdonb I'm afraid I didn't fully understand your suggestion. I'm currently using a monorepository for my k8s setup. It kind of looks like this:
* bootstrap -- Contains Flux bootstrap manifests
* infrastructure -- Contains infrastructure manifests
* apps -- Contains app manifests

My Kustomization dependency chain looks like this: bootstrap -> infrastructure -> apps

I'm currently using a single `GitRepository` resource that is used as source for all `Kustomization` resources. I understand that this is causing the issue, because a change in the single git repository means that every Kustomization needs to perform a dry-run and check for changes. Now, this is where I can't follow. What exactly are you suggesting to workaround this issue? Is there a solution without splitting my repository?

**Comment by kingdonb** [comment]
Yeah, depending on how firmly you are attached to the wording "without splitting up my repository"

You can split it up without splitting it up - publish the independent parts of your repository as separate OCI artifacts. Each independent part that you want to reconcile only the changes for that part can be published to its own OCI tag, you don't have to make this very complicated.

Each Flux Kustomization can sync from an OCIRepository with the changes for only its own part. This does not change the structure of the Git repository, only adds a bit of latency because you need to wait for GitHub Actions workflow to publish an OCI artifact with `flux push artifact`.

I can't speak for the usability of this yet as I'm not doing it, but I'll try it out, I think it should be reasonably good. You will not see blocking in the same places because only the parts with changes will block, and they will be delivered in different artifacts.

I think that's responsive to your problem, I have to grow my test environment a bit further until I have this problem again myself. I've shed a lot of infrastructure in the past 13 months or so!

**Comment by denniseffing** [comment]
Thanks for clarifying! I think before I introduce more complexity with publishing OCI artifacts it'd be easier to just split the repository instead. But definitely a viable approach if splitting your repository is not an option.
