### ISSUE TITLE
uninstall with --crds results in flux-system namespace stuck terminating

### ISSUE THREAD

**Issue by Nicklason** [fluxcd/flux2#632]
I have an RKE cluster and installed flux2 with the Flux CLI. When using the uninstall command with the --crds argument it removes all namespaces and CRDs as expected, but the flux-system namespace is stuck terminating. When removing the fluxcd labels from the namespace then the namespace is removed.

A workaround is to first run `flux uninstall` without the --crds argument. After that I can use `flux install --crds` to remove the CRDs.

**Comment by stefanprodan** [comment]
I can't reproduce this on Kubernetes Kind nor on GKE/EKS.

**Comment by mhenniges** [comment]
Got bit by a similar issue today, where I had bootstrapped flux via terraform, and then changed some arguments, so all the objects tried to get replaced (including the namespace), which never succeeded.

I believe this is because the deployments were successfully destroyed before some other objects, just as helmrepositories and helm releases, which are guarded with a finalizer. Without the flux2 pods running, there's nothing to clear the finalizer, so the objects and therefore the namespace is blocked from deleting.

**Comment by stefanprodan** [comment]
@mhenniges `flux uninstall` will not delete the pods until all finalizers are done, for Terraform see https://github.com/fluxcd/terraform-provider-flux/issues/67
