### ISSUE TITLE
Write instructions for bootstrapping using a writable git repository, for automation

### ISSUE THREAD

**Issue by squaremo** [fluxcd/flux2#799]
If you just use `flux bootstrap`, you get a read-only key for the git repository. Many people will run image update automation in the same place as syncing, and it would be convenient for them to be able to use a single git repository both for syncing and for automation -- which would need it to be writable.

**Comment by thanatchakromsang** [comment]
I have a question regarding this, is there a way to create a key with write permission with flux bootstrap? I have to manually update the permission of deploy token in GitLab

**Comment by squaremo** [comment]
Not yet, but there are at least instructions for replacing the secret: https://toolkit.fluxcd.io/guides/flux-v1-automation-migration/#replacing-the-git-credentials-secret

**Comment by nomeelnoj** [comment]
@squaremo correct me if I am wrong, but allowing a writable deploy key is as simple as modifying [this value](https://github.com/fluxcd/pkg/blob/main/git/provider_github.go#L173) to accept a flag, is it not? Is there a way we could expedite this feature request?

I really like the idea of being able to continue to use the bootstrap command for updates since flux2 is moving so fast and always releasing new functionality (thanks for this!).  But, currently in order to do that we have to either use a personal access token from an individual who may leave the company (service accounts are hard to come by in an Okta protected GitHub enterprise org due to MFA and all the extras required) or we have to setup a duplicate git repository source using our own custom managed deploy keys or user/service acct ssh keys, making this not work with the native functionality of the bootstrap command.  Any help would be greatly appreciated!

**Comment by squaremo** [comment]
> I really like the idea of being able to continue to use the bootstrap command for updates since flux2 is moving so fast

I see what you mean. If you replace the deploy key (per https://toolkit.fluxcd.io/guides/flux-v1-automation-migration/#replacing-the-git-credentials-secret), and install it in GitHub with the expected name, does it get overwritten by `flux bootstrap`?

The reason I held back from adding a flag for writable keys, is that I was not certain the automation would keep using GitRepository objects (see #665). But I suppose either way it might be useful to have the flag.

**Comment by stefanprodan** [comment]
Bootstrap will support configuring write access: https://github.com/fluxcd/flux2/pull/968
