### ISSUE TITLE
Flux v2 does not support specifying namespace of configMap in valuesFrom

### ISSUE THREAD

**Issue by sl4dy** [fluxcd/flux2#909]
### Describe the bug

The namespace selector is not supported in Helm Release valuesFrom section in Flux v2.

However, Flux v1 supports it:
https://docs.fluxcd.io/projects/helm-operator/en/stable/helmrelease-guide/values/#config-maps

### Expected behavior

Flux v2 supports namespace selector for configMap and possibly secret in valuesFrom section, same as Flux v1.
This might block the possibility to upgrade to Flux v2 for somebody (at least it does for us).

**Comment by hiddeco** [comment]
We are taking this into consideration for an upcoming release, see: https://github.com/fluxcd/helm-controller/pull/208

**Comment by hiddeco** [comment]
Note for people that find this issue later on due to e.g. SEO: the fact that things were supported in Flux v1 does not automatically mean they also will be or are supported in Flux v2.

Flux v2 is written from the ground up with a new design based on insights from developing Flux v1, this means that some things that were supported may not be in the newer version due to e.g. new insights around security or because we found another (often better) way to do things.
