### ISSUE TITLE
Default Manifest ClusterRolebinding objects hardcodes the flux-system namespace for all the service accounts

### ISSUE THREAD

**Issue by fcrespofastly** [fluxcd/flux2#989]
### Describe the bug

Default Manifest ClusterRolebinding objects hardcodes the flux-system namespace for all the service accounts

### To Reproduce

Steps to reproduce the behaviour:

1. Provide Flux install instructions

```cli
 flux bootstrap github --owner={{ flux_gh_org }} \
    --repository={{ flux_repository }} \
    --branch={{ flux_branch }} \
    --path=clusters/{{ cluster_name }}/ \
    --log-level=debug \
    --registry={{ registry }} \
    --image-pull-secret={{ image_pull_secret }} \
 ```
2. Provide a GitHub repository with Kubernetes manifests
It's on your own repo, your default manifests contains crb serviceaccount subjects with hardcoded namespace which caused errors in our entire fleet

### Expected behavior

Manifests to be installed using the provided namespace in the bootstrap command. It means that you should have templates and not raw manifests that you install.

### Additional context

- Kubernetes version: 1.18.4
- Git provider: Github
- Container registry provider: Harbor

Below please provide the output of the following commands:

```cli
flux --version
flux version 0.4.2
flux check --pre
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.18.14-gke.1200 >=1.16.0
✔ prerequisites checks passed
```

Can't really get the logs because I already fixed everything manually. But basically all the controllers service accounts were not able to watch cluster-scoped resources.

**Comment by stefanprodan** [comment]
This has been fixed, please update to latest flux version.

**Comment by bmnewson** [comment]
@stefanprodan can you confirm which version this has been fixed in please? we are still seeing it in:

flux --version
flux version 0.5.7

flux check -n infra-flux
► checking prerequisites
✔ kubectl 1.19.3 >=1.18.0
✔ Kubernetes 1.18.14-gke.1200 >=1.16.0
► checking controllers
✔ source-controller is healthy
► container-registry.secretcdn.net/external/fluxcd/source-controller:v0.9.0
✔ kustomize-controller is healthy
► container-registry.secretcdn.net/external/fluxcd/kustomize-controller:v0.9.1
✔ helm-controller is healthy
► container-registry.secretcdn.net/external/fluxcd/helm-controller:v0.8.0
✔ notification-controller is healthy
► container-registry.secretcdn.net/external/fluxcd/notification-controller:v0.9.0
✔ all checks passed

**Comment by stefanprodan** [comment]
flux version 0.9.0
